GET http://localhost:5000/detail/1

###
POST http://localhost:5000/logout

###
POST http://localhost:5000/login 
Content-Type: application/json

 {
    "email" : "phuocvungoc9997@gmail.com",
    "password" : "1"
 }

        
    
